import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google"
import { IBM_Plex_Mono } from "next/font/google";
import { Lexend } from "next/font/google";
 
import { cn } from "../lib/utils"

const lexend = Lexend({
    subsets: ["latin"],
    weight: ["400"],
    variable: "--font-lexend",
})

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background lexend antialiased dark overflow-x-hidden",
          fontSans.variable,
          lexend.variable
        )}>{children}</body>
    </html>
  );
}
